---

# This Playbook will define vairables and use them across the code

# HEADER SECTION
 - name: This play will install a package and copy a file
   hosts: webservers
   become: true
   vars:
     mypackage: vim
     myfile: /opt/ansible-code/playbook/helloworld.yml

# TASK SECTION
   tasks:
     - name: To install package named "{{ mypackage }}"
       apt:
         name: "{{ mypackage }}"
         state: present

     - name: To copy a file named "{{ myfile }}"
       copy:
         src: "/opt/{{ myfile }}"
         dest: "/opt/{{ myfile }}"
         mode: 0644
         owner: root
         group: root
